language: php

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm

sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
      if [[ "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      fi